Proyecto/urls.py
from django.contrib import admin
from django.urls import path
from Proyecto import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'Proyecto'

urlpatterns = [
    path('inicio/', views.inicio, name= "inicio"),
    path('acercademi/', views.acercaDeMi, name="acercaDeMi"),
    path('verPost/<int:pk>/', views.PostDetailView.as_view(), name='ver_posts'),
    path('pages/', views.lista_blogs, name='lista_blogs'),



    

    


] + static (settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

ProyectoFinal/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('Proyecto.urls')),
    path('', include ('accounts.urls')),
]

accounts/urls.py
from django.contrib import admin
from django.urls import path
from django import views
from django.conf import settings
from django.conf.urls.static import static
from accounts import views





app_name = 'accounts'

urlpatterns = [        
    path('login/', views.user_login, name= "login"),
    path('registro/', views.registro, name= "registro"),
    path('logout/', views.user_logout, name= "logout"),
    path('perfil/', views.perfil, name= "perfil"),
    path('perfil/editar/', views.editarPerfil, name="editarPerfil"),
    path('perfil/editar/', views.eliminar_perfil, name="borrarPerfil"),

    

    


] + static (settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

Proyecto/models.py
from django.db import models
from django.contrib.auth.models import User



class Post(models.Model):
    nombre = models.CharField(max_length= 30)
    titulo = models.CharField(max_length= 30)
    subtitulo = models.CharField(max_length= 30)
    cuerpo = models.TextField(max_length= 500)
    fecha = models.DateTimeField(auto_now_add=True)
    imagen = models.ImageField(upload_to='post_images/', null=True, blank= True)
    lugar = models.CharField(max_length= 40)
    


    def __str__(self) -> str:
        return f"Nombre: {self.nombre} - Titulo: {self.titulo}"
    


    


    

accounts/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver



class User_profile(models.Model):    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='profile_images/', null=True, blank= True)
    nombre = models.CharField(max_length= 40)
    descripcion = models.CharField(max_length=250)
    link = models.URLField(blank=True, null=True)
    correo = models.EmailField()
    contraseña = models.CharField(max_length=20)

    def __str__(self):
        return self.user.username









@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        User_profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.user.save()

accounts/forms.py
from django import forms


from .models import User_profile

class UserEditForm(forms.ModelForm):
    password = None
    correo = forms.EmailField()
    apellido = forms.CharField()
    nombre= forms.CharField()

    class Meta:
        model = User_profile
        fields = ['nombre','apellido', 'correo']

Proyecto/views.py
from django.shortcuts import  render, redirect
from Proyecto.models import *
from django.views.generic.detail import DetailView
from Proyecto.forms import *



def inicio (request):
    return render (request, 'Proyecto/index.html')


def acercaDeMi(request):
    return render(request, 'Proyecto/acercaDeMi.html')


class PostDetailView(DetailView):
    model= Post
    context_object_name= "posts"
    template_name = 'Proyecto/post_detail.html'

def lista_blogs(request):
    posts = Post.objects.all()
    return render (request, 'Proyecto/lista_blogs.html', {"posts": posts})

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import *
from .models import *
from django.contrib.auth.forms import  UserCreationForm
from django.contrib.auth import login as auth_login, authenticate, logout
from django.contrib import messages
from django.views.decorators.http import require_GET
from accounts.views import *
from django.core.exceptions import ObjectDoesNotExist


def user_login(request):  
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            auth_login(request, user)
            try:
                user_profile = user.userprofile
            except ObjectDoesNotExist:                
                User_profile.objects.create(user=user)
            return redirect('Proyecto:inicio')
        else:
            return render(request, 'Proyecto/login.html', {'error': 'Usuario o contraseña incorrectos'})
    return render(request, 'Proyecto/login.html')



def registro(request):    
    if request.method == 'POST':   
        form = UserCreationForm(request.POST)     
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('Proyecto:inicio')
        else:
            messages.error(request, 'Error en el formulario. Por favor, corrige los errores.')
    else:
        form = UserCreationForm()

    return render(request, 'Proyecto/registro.html', {"form": form})
    


@require_GET
def user_logout(request):
    logout(request)
    return redirect('Proyecto:inicio')

@login_required
def perfil(request):
    try:
        user_profile = request.user.userprofile
    except User_profile.DoesNotExist:        
        user_profile = None

    return render(request, 'Proyecto/perfil.html', {'user_profile': user_profile})
    


@login_required
def editarPerfil(request):
    usuario = request.user
    if request.method=='POST':
        mi_formulario = UserEditForm(request.POST, instance= request.user)

        if mi_formulario.is_valid():
            mi_formulario.save()
            return render (request, 'Proyecto/index.html')

    

@login_required
def eliminar_perfil(request):
    perfil = User_profile.objects.get(user=request.user)
    if request.method=="POST":
        perfil.delete()
        return redirect ('Proyecto:inicio')
    
    return render (request,'Proyecto/eliminar_perfil.html', {"perfil": perfil})

Proyecto/templates/Proyecto/acercaDeMi.html
{% extends 'Proyecto/padre.html'%}

{% load static %}

{% block content %}

<h1 style="color: black; text-align: center; text-decoration: underline;">Acerca de mí.</h1>
<h3 style="color:darkslategrey; text-align: justify"> Mi nombre es Leda, tengo 26 años y vivo en la provincia de Santa Cruz, Argentina.</h3>
    <p style="font-size:x-large; color: rgb(12, 12, 12 ); text-align: justify;">Descubrí el mundo de la programación en el año 2021 cuando cursé el primer año de Analista en Sistemas. 
    Iniciamos con el lenguaje C y es cuando supe que este mundo me iba a encantar. </p>
    <p style="font-size:x-large; color: rgb(12, 12, 12); text-align: justify;"> Realicé el curso de Java del INTI (ArgentinaPrograma) y en el mismo fue la primera vez que realicé un proyecto (Portfolio Web).
    A medida que avanzaron los años, he ido profundizando en diferentes lenguajes como Python y Java.</p>
    <p style="font-size:x-large; color: rgb(12, 12, 12); text-align: justify;">Este blog es un resultado de todo lo aprendido en el curso de Python que realicé en CoderHouse. Espero que disfruten de todo mi esfuerzo.</p>
    
{% endblock %}

Proyecto/templates/Proyecto/index.html
{% extends 'Proyecto/padre.html' %}

{% load static %}

{% block content %}

<h1 style="text-align: center; color: rgb(0, 0, 0);"> Espero que disfruten de mi blog. </h1>

<h2>En este blog encontrarás los distintos viajes que he realizado en los últimos años.</h2>

<p>Deseo que disfruten de mi contenido. </p>


{% endblock %}

Proyecto/templates/Proyecto/lista_blogs.html
{% extends 'Proyecto/padre.html' %}

{% load static %} 

{% block content %}

    <h1>Listado de Blogs</h1>

    {% if posts %}
        <ul>
            {% for p in posts %}
                <li>
                    <h2>{{ p.titulo }}</h2>
                    <h4>{{ p.subtitulo }} </h4>
                    <p> {{p.lugar }} </p>  
                    <a href="{% url 'Proyecto:ver_posts' p.id %}" class="btn btn-dark"> VER MAS </a>                 
                </li>
                
            {% endfor %}
        </ul>
    {% else %}
        <p>No hay blogs disponibles.</p>
    {% endif %}
{% endblock %}

Proyecto/templates/Proyecto/padre.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Blog Post - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'Proyecto/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'Proyecto:inicio' %}">BLOG DE VIAJES</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{% url 'Proyecto:inicio' %}">INICIO</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'Proyecto:acercaDeMi' %}">ACERCA DE MI</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'Proyecto:lista_blogs'%}">LISTA DE POSTS</a></li>                       
                        
                        {% if user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">LOGOUT </a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:perfil' %}"> PERFIL </a></li>
                            
                            
                        {% else %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">LOGIN </a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:registro' %}">REGISTRARSE </a></li>
                            
                        {% endif %}
                        
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}

        {% endblock %}
        
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">CURSO PYTHON CODERHOUSE - COMISION 56055 - 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'Proyecto/js/scripts.js' %}"></script>
    </body>
</html>

Proyecto/templates/Proyecto/post_detail.html
{% extends 'Proyecto/padre.html' %}

{% load static %}

{% block content %}
    <article>        
                <h1> {{posts.titulo}} </h1>
                <h2> {{posts.subtitulo}} </h2>
                <p> {{posts.cuerpo}} </p>
                <p style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;"> Fecha de publicacion: {{posts.fecha}} </p>
                <p> Lugar: {{ posts.lugar }}</p>
                {% if posts.imagen %}
                    <img src="{{posts.imagen.url}}" alt="imagen">
                {% endif %}
            
            {% if not posts %}
                <p> No hay blogs aún.</p>
            {% endif %}
        
    </article>




{% endblock %}

accounts/templates/Proyecto/editar_perfil.html
{% extends 'Proyecto/padre.html' %}

{% load static %}

{% block content %}
<h1> Editar perfil de {{usuario}} </h1>

<form action="" method="post">
    {% csrf_token %}

        <table>
            {{mi_formulario}}
        </table>

        <button type="submit" class="btn btn-dark"> GUARDAR CAMBIOS</button>
</form>

{% endblock %}

accounts/templates/Proyecto/eliminar_perfil.html
{% extends 'Proyecto/padre.html' %}

{% block content %}

<h1>Confirmar borrado de perfil</h1>
<br>
<p>¿Estás seguro de que deseas borrar tu perfil?</p>

<form method="post" action="{% url 'accounts:borrarPerfil' %}">

    {% csrf_token %}

    <button type="submit">Sí, borrar mi perfil</button>
    
    <a href="{% url 'accounts:perfil' %}">Cancelar</a>
</form>
{% endblock %}

accounts/templates/Proyecto/login.html
{% extends 'Proyecto/padre.html' %}

{% load static %}

{% block content %}

<h1> LOGIN </h1>
{% if error %}
<p> {{error}} </p>
{% endif %}
<form method="post">
    {% csrf_token %}
        
        <label for="username"> Usuario:</label>
        <input type="text" name="username" required>
        <br>
        <label for="password"> Contraseña:</label>
        <input type="password" name="password" required>
        <br>

        <button type="submit" class="btn btn-dark"> INICIAR SESION </button>
</form>
<br>
<a href="{% url 'accounts:registro' %}" class="btn btn-dark"> REGISTRARSE </a>

{% endblock %}

accounts/templates/Proyecto/perfil.html
{% extends 'Proyecto/padre.html' %}

{% load static %}

{% block content %}
<h1>Este es el perfil de {{user.username}} </h1>
<img src="profile.image.url" alt="foto de perfil">

<p> Nombre:  {{user_profile.nombre}} </p>
<p> Descripcion: {{user_profile.descripcion}}</p>
<p>Sitio web: <a href="{{ user_profile.link }}" target="_blank">{{ user_profile.link }}</a></p>
<p>Correo: {{user_profile.correo}} </p>
<p> Contraseña: {{user_profile.contraseña}} </p>



{% endblock %}

accounts/templates/Proyecto/registro.html
{% extends 'Proyecto/padre.html' %}

{% load static %}

{% block content %}
<div class="container">
    <h1>Registrar Usuario</h1>
    <form method="post">
        {% csrf_token %}
        <label for="email"> Correo:</label>
        <input type="email" name="email" required>
        <br>
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary"> Guardar </button>
    </form>
    <br>
    <a href="{% url 'accounts:login' %}" class="btn btn-dark"> INICIAR SESION </a>
    
</div>
{% endblock %}